config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  post '/recipes/friend_recipe' => "recipes#friend_recipe"
  resources :recipes
  resources :cuisines
  resources :food_types
  resources :food_preferences

  get '/users/:id' => "users#show"

  root 'home#index'

  post '/recipes/:id/favorites' => "recipes#favorites"
  #just to avoid colisions
  get  '/recipes/:id/favorites' => "recipes#show"
  get  '/recipes/:category/:id' => "recipes#categories"
end

app/controllers/food_types_controller.rb
class FoodTypesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_food_type, only: [:show, :edit, :update, :destroy]
  def new
    @food_type = FoodType.new
  end

  def create
    @food_type = FoodType.new(food_type_params)
    if @food_type.save
      redirect_to @food_type, notice: 'Food Type was successfully created.'
    else
      render :new
    end
  end

  def update
    if @food_type.update(food_type_params)
      redirect_to @food_type, notice: 'Food Type was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @food_type.destroy
    redirect_to food_type_url, notice: 'Food type was successfully destroyed.'
  end

  def edit
  end

  def index
    @food_types = FoodType.all
  end

  def show
  end

  private

  def set_food_type
    @food_type = FoodType.find(params[:id])
  end

  def food_type_params
    params.require(:food_type).permit(:name)
  end
end

app/helpers/food_types_helper.rb
module FoodTypesHelper
end

app/views/food_types/_form.html.erb
<%= form_for(@food_type) do |f| %>
  <% if @food_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_type.errors.count, "error") %> prohibited this Food Type from being saved:</h2>

      <ul>
      <% @food_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_types/edit.html.erb
<h1>Editing Food Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_type %> |
<%= link_to 'Back', food_types_path %>

app/views/food_types/index.html.erb
<p id="notice"><%= notice %></p>

<strong>Listing Food Type</strong>

<table>
  <tr>
    <th>Name</th>
    <th colspan="3">Actions</th>
  </tr>
  <% @food_types.each do |food_type| %>
    <tr>
      <td><%= food_type.name %></td>
      <td><%= link_to 'Show', food_type %></td>
      <td><%= link_to 'Edit', edit_food_type_path(food_type) %></td>
      <td><%= link_to 'Destroy', food_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/food_types/new.html.erb
<h1>New Food Type</h1>

<%= render 'form' %>

<%= link_to 'Back', food_type_path %>

app/views/food_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_type.name %>
</p>
<%= link_to 'Edit', edit_food_type_path(@food_type) %> |
<%= link_to 'Back', food_types_path %>