config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  post '/recipes/friend_recipe' => "recipes#friend_recipe"
  resources :recipes
  resources :cuisines
  resources :food_types
  resources :food_preferences

  get '/users/:id' => "users#show"

  root 'home#index'

  post '/recipes/:id/favorites' => "recipes#favorites"
  #just to avoid colisions
  get  '/recipes/:id/favorites' => "recipes#show"
  get  '/recipes/:category/:id' => "recipes#categories"
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates_presence_of :name, :cuisine, :food_type, :food_preference, :ingredients, :procedure
  has_and_belongs_to_many :users_who_liked, class_name: "User"
  belongs_to :food_preference
  belongs_to :food_type
  belongs_to :cuisine
  belongs_to :user
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  def self.most_favorites
    joins(:users_who_liked).select("count(*) as num_of_favorites, recipes.*").group("recipes_users.recipe_id, recipes.id").order("1 desc")
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :favorites]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :favorites, :friend_recipe]

  # GET /recipes
  def index
    @recipes = Recipe.all
  end

  def favorites
    user = current_user
    user.favorites << @recipe
    redirect_to @recipe
  end

  def categories
    category = params[:category].to_sym
    @recipes = Recipe.where(category => params[:id])
    @type_name = @recipes.first.send(category).name unless @recipes.size == 0
    render template: "recipes/index"
  end

  # GET /recipes/1
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)
    set_relationship
    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /recipes/1
  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  def friend_recipe
    user = current_user
    email = params[:email]
    message = params[:message]
    FriendMailer.recipe_mail(email, user, @recipe, message).deliver
    render :nothing => true
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_relationship
    @recipe.user = current_user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:name, :serves, :cooking_time, :difficulty, :ingredients, :procedure, :food_preference_id, :food_type_id, :cuisine_id, :photo)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :serves %><br>
    <%= f.number_field :serves, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :food_preference %><br>
    <%= f.collection_select(:food_preference_id, FoodPreference.all, :id, :name, {prompt: "Selecione"}, class: "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label :food_type %><br>
    <%= f.collection_select(:food_type_id, FoodType.all, :id, :name, {prompt: "Selecione"}, class: "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label :cuisine %><br>
    <%= f.collection_select(:cuisine_id, Cuisine.all, :id, :name, {prompt: "Selecione"}, class: "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label :cooking_time %><br>
    <%= f.number_field :cooking_time, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :difficulty %><br>
    <%= f.select :difficulty, [["Fácil","Fácil"],["Médio","Médio"],["Dificil","Dificil"]], {prompt: "Selecione dificuldade"}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :procedure %><br>
    <%= f.text_area :procedure, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :photo %><br>
    <%= f.file_field :photo, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h2><%= "#{@type_name.capitalize}" if @type_name %> Recipes </h2>
<%= render partial: "shared/recipe_in_a_list", collection: @recipes, as: :recipe %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<%if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @recipe.name %></h3>
  </div>
  <div class="panel-body">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          <p><strong>Sent by:</strong> <%= link_to @recipe.user.name, "/users/#{@recipe.user.id}" %></p>
          <p><strong>Preference:</strong> <%= @recipe.food_preference.name %></p>
          <p><strong>Cuisine:</strong> <%= @recipe.cuisine.name %></p>
          <p><strong>Type:</strong> <%= @recipe.food_type.name %></p>
          <p><strong>Serves:</strong> <%= pluralize(@recipe.serves, "person")%></p>
          <p><strong>Cooking Time:</strong> <%= @recipe.cooking_time %> minutes</p>
          <p><strong>Difficulty:</strong> <%= @recipe.difficulty %></p>
        </div>
        <div class="col-md-6">
          <%= image_tag @recipe.photo.url(:medium), class: "image-responsive" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <p><strong>Ingredients:</strong></p>
          <ul>
            <% @recipe.ingredients.split("\r\n").each do |step| %>
              <li><%= step %></li>
            <% end %>
          </ul>
        </div>
        <div class="col-md-6">
          <p><strong>Procedure</strong></p>
          <ul>
            <% @recipe.procedure.split("\r\n").each do |step| %>
              <li><%= step %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="row">
        <% unless @recipe.users_who_liked && @recipe.users_who_liked.include?(current_user) %>
        <div class="col-md-3">
          <%= link_to "Favorite it!", "/recipes/#{@recipe.id}/favorites", method: :post %>
        </div>
        <% end %>
        <div class="col-md-3">
          <a href="#" data-toggle="modal" data-target="#exampleModal">Send to a friend!</a>

          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="exampleModalLabel">New message</h4>
                </div>
                <div class="modal-body">
                  <form>
                    <div class="form-group">
                      <label for="recipient-name" class="control-label">Recipient:</label>
                      <input type="text" class="form-control" id="recipient-name">
                    </div>
                    <div class="form-group">
                      <label for="message-text" class="control-label">Message:</label>
                      <textarea class="form-control" id="message-text"></textarea>
                    </div>
                    <input type="hidden" id="recipe-id" value="<%= @recipe.id %>">
                  </form>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal" id="close-btn">Close</button>
                  <button type="button" class="btn btn-primary" id="send-email-btn">Send message</button>
                </div>
              </div>
            </div>
          </div><!-- fim modal email -->
        </div>
      </div>
    </div>
  </div>
</div>

<% if user_signed_in? && current_user == @recipe.user %>
  <%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<% end %>
<%= link_to '<< More recipes', recipes_path %>