config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  post '/recipes/friend_recipe' => "recipes#friend_recipe"
  resources :recipes
  resources :cuisines
  resources :food_types
  resources :food_preferences

  get '/users/:id' => "users#show"

  root 'home#index'

  post '/recipes/:id/favorites' => "recipes#favorites"
  #just to avoid colisions
  get  '/recipes/:id/favorites' => "recipes#show"
  get  '/recipes/:category/:id' => "recipes#categories"
end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  validates_presence_of :name
  has_many :recipes
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_cuisine, only: [:show, :edit, :update, :destroy]
  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new(cuisine_params)
    if @cuisine.save
      redirect_to @cuisine, notice: 'Cuisine was successfully created.'
    else
      render :new
    end
  end

  def update
    if @cuisine.update(cuisine_params)
      redirect_to @cuisine, notice: 'Cuisine was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @cuisine.destroy
    redirect_to cuisine_url, notice: 'Cuisine was successfully destroyed.'
  end

  def edit
  end

  def index
    @cuisines = Cuisine.all
  end

  def show
  end

  private

  def set_cuisine
    @cuisine = Cuisine.find(params[:id])
  end

  def cuisine_params
    params.require(:cuisine).permit(:name)
  end
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/views/cuisines/_form.html.erb
<%= form_for(@cuisine) do |f| %>
  <% if @cuisine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cuisine.errors.count, "error") %> prohibited this cuisine from being saved:</h2>

      <ul>
      <% @cuisine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cuisines/edit.html.erb
<h1>Editing Cuisine</h1>

<%= render 'form' %>

<%= link_to 'Show', @cuisine %> |
<%= link_to 'Back', cuisines_path %>

app/views/cuisines/index.html.erb
<p id="notice"><%= notice %></p>

<strong>Listing Cuisines</strong>

<table>
  <tr>
    <th>Name</th>
    <th colspan="3">Actions</th>
  </tr>
  <% @cuisines.each do |cuisine| %>
    <tr>
      <td><%= cuisine.name %></td>
      <td><%= link_to 'Show', cuisine %></td>
      <td><%= link_to 'Edit', edit_cuisine_path(cuisine) %></td>
      <td><%= link_to 'Destroy', cuisine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/cuisines/new.html.erb
<h1>New Cuisine</h1>

<%= render 'form' %>

<%= link_to 'Back', cuisine_path %>

app/views/cuisines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cuisine.name %>
</p>
<%= link_to 'Edit', edit_cuisine_path(@cuisine) %> |
<%= link_to 'Back', cuisines_path %>