config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  post '/recipes/friend_recipe' => "recipes#friend_recipe"
  resources :recipes
  resources :cuisines
  resources :food_types
  resources :food_preferences

  get '/users/:id' => "users#show"

  root 'home#index'

  post '/recipes/:id/favorites' => "recipes#favorites"
  #just to avoid colisions
  get  '/recipes/:id/favorites' => "recipes#show"
  get  '/recipes/:category/:id' => "recipes#categories"
end

app/models/food_preference.rb
class FoodPreference < ActiveRecord::Base
  validates_presence_of :name
  has_many :recipes
end

app/controllers/food_preferences_controller.rb
class FoodPreferencesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_food_preference, only: [:show, :edit, :update, :destroy]
  def new
    @food_preference = FoodPreference.new
  end

  def create
    @food_preference = FoodPreference.new(food_preference_params)
    if @food_preference.save
      redirect_to @food_preference, notice: 'Food Preference was successfully created.'
    else
      render :new
    end
  end

  def update
    if @food_preference.update(food_preference_params)
      redirect_to @food_preference, notice: 'Food Preference was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @food_preference.destroy
    redirect_to food_preference_url, notice: 'Food type was successfully destroyed.'
  end

  def edit
  end

  def index
    @food_preferences = FoodPreference.all
  end

  def show
  end

  private

  def set_food_preference
    @food_preference = FoodPreference.find(params[:id])
  end

  def food_preference_params
    params.require(:food_preference).permit(:name)
  end
end

app/helpers/food_preferences_helper.rb
module FoodPreferencesHelper
end

app/views/food_preferences/_form.html.erb
<%= form_for(@food_preference) do |f| %>
  <% if @food_preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_preference.errors.count, "error") %> prohibited this Food Preference from being saved:</h2>

      <ul>
      <% @food_preference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_preferences/edit.html.erb
<h1>Editing Food Preference</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_preference %> |
<%= link_to 'Back', food_preferences_path %>

app/views/food_preferences/index.html.erb
<p id="notice"><%= notice %></p>

<strong>Listing Food Preference</strong>

<table>
  <tr>
    <th>Name</th>
    <th colspan="3">Actions</th>
  </tr>
  <% @food_preferences.each do |food_preference| %>
    <tr>
      <td><%= food_preference.name %></td>
      <td><%= link_to 'Show', food_preference %></td>
      <td><%= link_to 'Edit', edit_food_preference_path(food_preference) %></td>
      <td><%= link_to 'Destroy', food_preference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/food_preferences/new.html.erb
<h1>New Food Preference</h1>

<%= render 'form' %>

<%= link_to 'Back', food_preference_path %>

app/views/food_preferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_preference.name %>
</p>
<%= link_to 'Edit', edit_food_preference_path(@food_preference) %> |
<%= link_to 'Back', food_preferences_path %>